#ifndef DECODER_CTL_H
#define DECODER_CTL_H

#ifdef  __cplusplus
extern "C" {
#endif
int media_set_decoder_stat(u32 val);
int media_get_decoder_stat();
int media_set_decoder_error_recovery_mode(u32 val);
int media_get_decoder_error_recovery_mode();
int media_set_decoder_sync_outside(u32 val);
int media_get_decoder_sync_outside();
int media_set_decoder_dec_control(u32 val);
int media_get_decoder_dec_control();
int media_set_decoder_fatal_error_reset(u32 val);
int media_get_decoder_fatal_error_reset();
int media_set_decoder_max_refer_buf(u32 val);
int media_get_decoder_max_refer_buf();
int media_set_decoder_ucode_type(u32 val);
int media_get_decoder_ucode_type();
int media_set_decoder_debugfirmware(u32 val);
int media_get_decoder_debugfirmware();
int media_set_decoder_fixed_frame_rate_val(u32 val);
int media_get_decoder_fixed_frame_rate_val();
int media_set_decoder_decoder_debug_val(u32 val);
int media_get_decoder_decoder_debug_val();
int media_set_decoder_dpb_size_adj(u32 val);
int media_get_decoder_dpb_size_adj();
int media_set_decoder_decoder_force_reset(u32 val);
int media_get_decoder_decoder_force_reset();
int media_set_decoder_no_idr_error_max(u32 val);
int media_get_decoder_no_idr_error_max();
int media_set_decoder_enable_switch_fense(u32 val);
int media_get_decoder_enable_switch_fense();
int media_set_decoder_debug_trace_num(u32 val);
int media_get_decoder_debug_trace_num();
int media_set_decoder_hevc_max_reset_count(u32 val);
int media_get_decoder_hevc_max_reset_count();
int media_set_decoder_clk_config(u32 val);
int media_get_decoder_clk_config();
int media_set_decoder_step_mode(u32 val);
int media_get_decoder_step_mode();
int media_set_decoder_mpeg12_stat(u32 val);
int media_get_decoder_mpeg12_stat();
int media_set_decoder_mpeg12_dec_control(u32 val);
int media_get_decoder_mpeg12_dec_control();
int media_set_decoder_mpeg12_error_frame_skip_level(u32 val);
int media_get_decoder_mpeg12_error_frame_skip_level();
int media_set_decoder_mpeg4_stat(u32 val);
int media_get_decoder_mpeg4_stat();
int media_set_decoder_h265_use_cma(u32 val);
int media_get_decoder_h265_use_cma();
int media_set_decoder_h265_bit_depth_luma(u32 val);
int media_get_decoder_h265_bit_depth_luma();
int media_set_decoder_h265_video_signal_type(u32 val);
int media_get_decoder_h265_video_signal_type();
int media_set_decoder_h265_dbg_nal_skip_val(u32 val);
int media_get_decoder_h265_dbg_nal_skip_val();
int media_set_decoder_h265_dbg_nal_skip_count(u32 val);
int media_get_decoder_h265_dbg_nal_skip_count();
int media_set_decoder_h265_radr(u32 val);
int media_get_decoder_h265_radr();
int media_set_decoder_h265_rval(u32 val);
int media_get_decoder_h265_rval();
int media_set_decoder_h265_dbg_cmd(u32 val);
int media_get_decoder_h265_dbg_cmd();
int media_set_decoder_h265_dbg_skip_decode_index(u32 val);
int media_get_decoder_h265_dbg_skip_decode_index();
int media_set_decoder_h265_endian(u32 val);
int media_get_decoder_h265_endian();
int media_set_decoder_h265_step(u32 val);
int media_get_decoder_h265_step();
int media_set_decoder_h265_decode_stop_pos(u32 val);
int media_get_decoder_h265_decode_stop_pos();
int media_set_decoder_h265_decode_pic_begin(u32 val);
int media_get_decoder_h265_decode_pic_begin();
int media_set_decoder_h265_slice_parse_begin(u32 val);
int media_get_decoder_h265_slice_parse_begin();
int media_set_decoder_h265_nal_skip_policy(u32 val);
int media_get_decoder_h265_nal_skip_policy();
int media_set_decoder_h265_i_only_val(u32 val);
int media_get_decoder_h265_i_only_val();
int media_set_decoder_h265_error_handle_policy(u32 val);
int media_get_decoder_h265_error_handle_policy();
int media_set_decoder_h265_error_handle_threshold(u32 val);
int media_get_decoder_h265_error_handle_threshold();
int media_set_decoder_h265_handle_nal_skip_threshold(u32 val);
int media_get_decoder_h265_handle_nal_skip_threshold();
int media_set_decoder_h265_error_handle_system_threshold(u32 val);
int media_get_decoder_h265_error_handle_system_threshold();
int media_set_decoder_h265_error_skip_nal_count(u32 val);
int media_get_decoder_h265_error_skip_nal_count();
int media_set_decoder_h265_debug(u32 val);
int media_get_decoder_h265_debug();
int media_set_decoder_h265_debug_mask(u32 val);
int media_get_decoder_h265_debug_mask();
int media_set_decoder_h265_buffer_mode(u32 val);
int media_get_decoder_h265_buffer_mode();
int media_set_decoder_h265_double_write_mode(u32 val);
int media_get_decoder_h265_double_write_mode();
int media_set_decoder_h265_buf_alloc_width(u32 val);
int media_get_decoder_h265_buf_alloc_width();
int media_set_decoder_h265_buf_alloc_height(u32 val);
int media_get_decoder_h265_buf_alloc_height();
int media_set_decoder_h265_dynamic_buf_num_margin(u32 val);
int media_get_decoder_h265_dynamic_buf_num_margin();
int media_set_decoder_h265_max_buf_num(u32 val);
int media_get_decoder_h265_max_buf_num();
int media_set_decoder_h265_buf_alloc_size(u32 val);
int media_get_decoder_h265_buf_alloc_size();
int media_set_decoder_h265_buffer_mode_dbg(u32 val);
int media_get_decoder_h265_buffer_mode_dbg();
int media_set_decoder_h265_mem_map_mode(u32 val);
int media_get_decoder_h265_mem_map_mode();
int media_set_decoder_h265_enable_mem_saving(u32 val);
int media_get_decoder_h265_enable_mem_saving();
int media_set_decoder_h265_force_w_h(u32 val);
int media_get_decoder_h265_force_w_h();
int media_set_decoder_h265_force_fps(u32 val);
int media_get_decoder_h265_force_fps();
int media_set_decoder_h265_max_decoding_time(u32 val);
int media_get_decoder_h265_max_decoding_time();
int media_set_decoder_h265_prefix_aux_buf_size(u32 val);
int media_get_decoder_h265_prefix_aux_buf_size();
int media_set_decoder_h265_suffix_aux_buf_size(u32 val);
int media_get_decoder_h265_suffix_aux_buf_size();
int media_set_decoder_h265_interlace_enable(u32 val);
int media_get_decoder_h265_interlace_enable();
int media_set_decoder_h265_pts_unstable(u32 val);
int media_get_decoder_h265_pts_unstable();
int media_set_decoder_h265_parser_sei_enable(u32 val);
int media_get_decoder_h265_parser_sei_enable();
int media_set_decoder_h265_start_decode_buf_level(u32 val);
int media_get_decoder_h265_start_decode_buf_level();
int media_set_decoder_h265_decode_timeout_val(u32 val);
int media_get_decoder_h265_decode_timeout_val();
int media_set_decoder_h265_parser_dolby_vision_enable(u32 val);
int media_get_decoder_h265_parser_dolby_vision_enable();
int media_set_decoder_h265_dv_toggle_prov_name(u32 val);
int media_get_decoder_h265_dv_toggle_prov_name();
int media_set_decoder_h265_dv_debug(u32 val);
int media_get_decoder_h265_dv_debug();
int media_set_decoder_vp9_bit_depth_luma(u32 val);
int media_get_decoder_vp9_bit_depth_luma();
int media_set_decoder_vp9_bit_depth_chroma(u32 val);
int media_get_decoder_vp9_bit_depth_chroma();
int media_set_decoder_vp9_frame_width(u32 val);
int media_get_decoder_vp9_frame_width();
int media_set_decoder_vp9_frame_height(u32 val);
int media_get_decoder_vp9_frame_height();
int media_set_decoder_vp9_debug(u32 val);
int media_get_decoder_vp9_debug();
int media_set_decoder_vp9_radr(u32 val);
int media_get_decoder_vp9_radr();
int media_set_decoder_vp9_rval(u32 val);
int media_get_decoder_vp9_rval();
int media_set_decoder_vp9_pop_shorts(u32 val);
int media_get_decoder_vp9_pop_shorts();
int media_set_decoder_vp9_dbg_cmd(u32 val);
int media_get_decoder_vp9_dbg_cmd();
int media_set_decoder_vp9_dbg_skip_decode_index(u32 val);
int media_get_decoder_vp9_dbg_skip_decode_index();
int media_set_decoder_vp9_endian(u32 val);
int media_get_decoder_vp9_endian();
int media_set_decoder_vp9_step(u32 val);
int media_get_decoder_vp9_step();
int media_set_decoder_vp9_decode_stop_pos(u32 val);
int media_get_decoder_vp9_decode_stop_pos();
int media_set_decoder_vp9_decode_pic_begin(u32 val);
int media_get_decoder_vp9_decode_pic_begin();
int media_set_decoder_vp9_slice_parse_begin(u32 val);
int media_get_decoder_vp9_slice_parse_begin();
int media_set_decoder_vp9_error_handle_policy(u32 val);
int media_get_decoder_vp9_error_handle_policy();
int media_set_decoder_vp9_buf_alloc_width(u32 val);
int media_get_decoder_vp9_buf_alloc_width();
int media_set_decoder_vp9_buf_alloc_depth(u32 val);
int media_get_decoder_vp9_buf_alloc_depth();
int media_set_decoder_vp9_buf_alloc_size(u32 val);
int media_get_decoder_vp9_buf_alloc_size();
int media_set_decoder_vp9_buffer_mode(u32 val);
int media_get_decoder_vp9_buffer_mode();
int media_set_decoder_vp9_buffer_mode_dbg(u32 val);
int media_get_decoder_vp9_buffer_mode_dbg();
int media_set_decoder_vp9_max_buf_num(u32 val);
int media_get_decoder_vp9_max_buf_num();
int media_set_decoder_vp9_dynamic_buf_num_margin(u32 val);
int media_get_decoder_vp9_dynamic_buf_num_margin();
int media_set_decoder_vp9_mem_map_mode(u32 val);
int media_get_decoder_vp9_mem_map_mode();
int media_set_decoder_vp9_double_write_mode(u32 val);
int media_get_decoder_vp9_double_write_mode();
int media_set_decoder_vp9_enable_mem_saving(u32 val);
int media_get_decoder_vp9_enable_mem_saving();
int media_set_decoder_vp9_force_w_h(u32 val);
int media_get_decoder_vp9_force_w_h();
int media_set_decoder_vp9_force_fps(u32 val);
int media_get_decoder_vp9_force_fps();
int media_set_decoder_vp9_max_decoding_time(u32 val);
int media_get_decoder_vp9_max_decoding_time();
int media_set_decoder_vp9_on_no_keyframe_skiped(u32 val);
int media_get_decoder_vp9_on_no_keyframe_skiped();
int media_set_decoder_vp9_start_decode_buf_level(u32 val);
int media_get_decoder_vp9_start_decode_buf_level();
int media_set_decoder_vp9_decode_timeout_val(u32 val);
int media_get_decoder_vp9_decode_timeout_val();
int media_set_decoder_avs_stat(u32 val);
int media_get_decoder_avs_stat();
int media_set_decoder_avs_debug_val(u32 val);
int media_get_decoder_avs_debug_val();
int media_set_decoder_avs_error_recovery_mode(u32 val);
int media_get_decoder_avs_error_recovery_mode();
int media_set_decoder_avs_pic_type(u32 val);
int media_get_decoder_avs_pic_type();
int media_set_decoder_avs_radr(u32 val);
int media_get_decoder_avs_radr();
int media_set_decoder_avs_vf_buf_num(u32 val);
int media_get_decoder_avs_vf_buf_num();
int media_set_decoder_avs_vf_buf_num_used(u32 val);
int media_get_decoder_avs_vf_buf_num_used();
int media_set_decoder_avs_canvas_base(u32 val);
int media_get_decoder_avs_canvas_base();
int media_set_decoder_avs_work_buf_size(u32 val);
int media_get_decoder_avs_work_buf_size();
int media_set_decoder_avs_firmware_sel(u32 val);
int media_get_decoder_avs_firmware_sel();
int media_set_decoder_jpeg_debug_val(u32 val);
int media_get_decoder_jpeg_debug_val();
int media_set_decoder_jpeg_dump_file_val(u32 val);
int media_get_decoder_jpeg_dump_file_val();
int media_set_decoder_jpeg_p2p_mode(u32 val);
int media_get_decoder_jpeg_p2p_mode();
int media_set_decoder_jpeg_output_format_mode(u32 val);
int media_get_decoder_jpeg_output_format_mode();
#ifdef  __cplusplus
}
#endif
#endif